version: '3'
services:
  jobmanager:
    image: flink:1.9.0-scala_2.11
    container_name: jobmanager
    expose:
    - "6123"
    ports:
    - "8081:8081"
    command: jobmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS : ${JOB_MANAGER_RPC_ADDRESS}
    volumes:
    - ./${DATA_DIR}/:/opt/flink/${DATA_DIR}/
    - ./${DATA_DIR}/log:/opt/flink/log
  taskmanager:
    image: flink:1.9.0-scala_2.11
    container_name: taskmanager
    expose:
    - "6121"
    - "6122"
    depends_on:
    - jobmanager
    command: taskmanager
    links:
    - "jobmanager:jobmanager"
    environment:
      JOB_MANAGER_RPC_ADDRESS: ${JOB_MANAGER_RPC_ADDRESS}
    volumes:
    - ./${DATA_DIR}/:/opt/flink/${DATA_DIR}/
    - ./${DATA_DIR}/log:/opt/flink/log

networks:
  default:
    external:
      name: ${NETWORK_NAME}